### ISSUE TITLE
Syntax highlighting for other languages

### ISSUE THREAD

**Issue by mbutterick** [stamourv/java-lexer#1]
Is there anything in `java-lexer` that could be adapted to a general-purpose syntax highlighter? I assume not, since it seems to rely heavily on the Java-specific `profj` for the heavy lifting,

**Comment by stamourv** [comment]
I suspect the scaffolding would be roughly the same, but beyond that, I don't expect much reuse.

The java lexer itself is surprisingly versatile, though. I use it to highlight JavaScript and it looks just fine. I've also used it for some Haskell code, which was a stretch, but looked ok.
